name: "screenshots-action"
description: "Screenshot a website with different viewpoints : from https://github.com/flameddd/screenshots-ci-action"
author: "Barnando Akbarto Hidayatullah <barnando13@gmail.com>"
branding:
  icon: 'monitor'
  color: 'blue'
inputs:
  url:
    required: true
    description: "The website URL you want to screenshot. e.x.: https://www.google.com/"
  noDesktop:
    required: false
    description: "Not screenshot website's desktop viewpoint"
    default: "false"
  devices:
    required: false
    description: "Screenshot specific mobile devices viewpoint. e.x.: 'iPhone 12' 'iPhone 12 landscape' 'iPad Pro landscape'"
  fullPage:
    required: false
    description: "When true, takes a screenshot of the full scrollable page. Defaults to false"
    default: "false"
  type:
    required: false
    description: "Specify screenshot type, can be either jpeg or png. Defaults to 'jpeg'."
    default: 'jpeg'
runs:
  using: "node12"
  main: "dist/index.js"